---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart postfix
  service: name=postfix state=restarted
  when: postfix_service_state != 'stopped'
